import { useState, useRef, useEffect, useCallback } from 'react';
import { Share2, Download, ChevronDown, FileText, Clock, Plus, Trash2, Edit3, Save } from 'lucide-react';
import { useTheme } from '../contexts/ThemeContext';
import HexagonalLoader from './HexagonalLoader';
import WordDocEditor from './WordDocEditor';

interface DOCSection {
    heading: string;
    content: string;
}

interface DOCDocument {
    title: string;
    author: string;
    sections: DOCSection[];
    grapesHtml?: string;
    grapesCss?: string;
}

interface HistoryItem {
    id: string;
    title: string;
    document: DOCDocument;
    createdAt: string;
}

interface DOCPreviewProps {
    document: DOCDocument | null;
    isLoading?: boolean;
}

const HISTORY_KEY = 'pagecrafter_doc_history';

function getHistory(): HistoryItem[] {
    if (typeof window === 'undefined') return [];
    try {
        const data = localStorage.getItem(HISTORY_KEY);
        return data ? JSON.parse(data) : [];
    } catch {
        return [];
    }
}

function saveToHistory(doc: DOCDocument): void {
    const history = getHistory();
    const item: HistoryItem = {
        id: Date.now().toString(),
        title: doc.title,
        document: doc,
        createdAt: new Date().toISOString(),
    };
    // Keep max 20 items
    const updated = [item, ...history].slice(0, 20);
    localStorage.setItem(HISTORY_KEY, JSON.stringify(updated));
}

export default function DOCPreview({ document: initialDoc, isLoading }: DOCPreviewProps) {
    const { theme } = useTheme();
    const [doc, setDoc] = useState<DOCDocument | null>(initialDoc);
    const [isShareMenuOpen, setIsShareMenuOpen] = useState(false);
    const [isHistoryOpen, setIsHistoryOpen] = useState(false);
    const [isEditorOpen, setIsEditorOpen] = useState(false);
    const [history, setHistory] = useState<HistoryItem[]>([]);
    const shareMenuRef = useRef<HTMLDivElement>(null);
    const historyMenuRef = useRef<HTMLDivElement>(null);

    // Update doc when new one is generated
    useEffect(() => {
        if (initialDoc) {
            setDoc(initialDoc);
            saveToHistory(initialDoc);
            setHistory(getHistory());
        }
    }, [initialDoc]);

    // Load history on mount
    useEffect(() => {
        setHistory(getHistory());
    }, []);

    useEffect(() => {
        function handleClickOutside(event: MouseEvent) {
            if (shareMenuRef.current && !shareMenuRef.current.contains(event.target as Node)) {
                setIsShareMenuOpen(false);
            }
            if (historyMenuRef.current && !historyMenuRef.current.contains(event.target as Node)) {
                setIsHistoryOpen(false);
            }
        }
        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, []);

    const renderContent = (content: any): string => {
        if (typeof content === 'string') return content;
        if (Array.isArray(content)) return content.join('\n');
        if (typeof content === 'object' && content !== null) {
            return Object.entries(content)
                .map(([key, value]) => `${key}: ${typeof value === 'object' ? JSON.stringify(value) : value}`)
                .join('\n');
        }
        return String(content || '');
    };

    const convertToInitialHtml = (d: DOCDocument) => {
        let html = `<div id="wrapper">`;
        
        // Header with Emerald Branding
        html += `
            <div class="emerald-title-block">
                <h1 class="emerald-title">${renderContent(d.title)}</h1>
                <div class="emerald-meta">
                    <span>By ${d.author || 'PageCrafter AI'}</span>
                    <span>${new Date().toLocaleDateString()}</span>
                </div>
            </div>
        `;
        
        // Sections with Emerald Branding
        d.sections.forEach(section => {
            html += `
                <div class="section-block" style="margin-bottom: 32px;">
                    <div class="emerald-heading-block">
                        <h2 class="emerald-heading">${renderContent(section.heading)}</h2>
                    </div>
                    <div>
                        <p style="margin-bottom: 16px;">${renderContent(section.content)}</p>
                    </div>
                </div>
            `;
        });
        
        // Footer
        html += `
            <div style="margin-top: 64px; padding-top: 40px; border-top: 1px solid #f3f4f6; display: flex; justify-content: space-between; align-items: center; font-size: 10px; font-weight: 900; color: #d1d5db; text-transform: uppercase; letter-spacing: 0.3em;">
                <span>Generated by PageCrafter AI — Doc Maker</span>
                <span>Page 1 of 1</span>
            </div>
        `;
        
        html += `</div>`;
        return html;
    };

    const handleOpenEditor = () => {
        if (!doc) return;
        if (!doc.grapesHtml) {
            setDoc({
                ...doc,
                grapesHtml: convertToInitialHtml(doc)
            });
        }
        setIsEditorOpen(true);
    };

    const handleSaveFromEditor = (html: string) => {
        if (!doc) return;
        const updatedDoc = { ...doc, grapesHtml: html }; // Keep grapesHtml name for backward compatibility or rename to docHtml
        setDoc(updatedDoc);
        saveToHistory(updatedDoc);
        setHistory(getHistory());
        setIsEditorOpen(false);
    };

    const loadFromHistory = (item: HistoryItem) => {
        setDoc(item.document);
        setIsHistoryOpen(false);
    };

    const handleExportDOCX = async () => {
        if (!doc) return;

        try {
            const docxLib = await import('docx');
            const { Document, Packer, Paragraph, TextRun, HeadingLevel, BorderStyle } = docxLib;

            const children: any[] = [];

            if (doc.grapesHtml) {
                // If we edited with GrapesJS, we try to parse the content
                // For a robust export, we extract text from the HTML structure
                const container = window.document.createElement('div');
                container.innerHTML = doc.grapesHtml;
                
                const processNode = (node: Node) => {
                    if (node.nodeType === Node.TEXT_NODE) return;
                    
                    const el = node as HTMLElement;
                    
                    // Priority: Class based (Emerald) -> Original Tag based
                    if (el.tagName === 'H1' || el.classList?.contains('emerald-title')) {
                        children.push(new Paragraph({
                            children: [new TextRun({ text: el.textContent || '', bold: true, size: 48, color: '111827' })],
                            spacing: { after: 300 }
                        }));
                    } else if (el.tagName === 'H2' || el.classList?.contains('emerald-heading')) {
                        children.push(new Paragraph({
                            children: [new TextRun({ text: el.textContent || '', bold: true, size: 32, color: '059669' })],
                            spacing: { before: 400, after: 200 }
                        }));
                    } else if (el.tagName === 'P' || el.tagName === 'LI') {
                        if (el.textContent?.trim()) {
                            children.push(new Paragraph({
                                children: [new TextRun({ text: el.textContent || '', size: 24, color: '374151' })],
                                spacing: { after: 200 },
                                bullet: el.tagName === 'LI' ? { level: 0 } : undefined
                            }));
                        }
                    } else {
                        // Recurse for wrappers
                        el.childNodes.forEach(processNode);
                    }
                };

                processNode(container);
            } else {
                // Standard structured export
                children.push(
                    new Paragraph({
                        children: [
                            new TextRun({
                                text: doc.title || "Untitled Document",
                                bold: true,
                                size: 52,
                                color: '059669',
                            }),
                        ],
                        spacing: { after: 200 },
                        border: {
                            bottom: { color: '059669', space: 8, style: BorderStyle.SINGLE, size: 12 },
                        },
                    })
                );

                children.push(
                    new Paragraph({
                        children: [
                            new TextRun({
                                text: `By ${doc.author || 'PageCrafter AI'}  •  ${new Date().toLocaleDateString()}`,
                                size: 20,
                                color: '666666',
                            }),
                        ],
                        spacing: { after: 400 },
                    })
                );

                doc.sections.forEach((section) => {
                    children.push(
                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: section.heading || "Section",
                                    bold: true,
                                    size: 28,
                                    color: '059669',
                                }),
                            ],
                            heading: HeadingLevel.HEADING_2,
                            spacing: { before: 360, after: 160 },
                        })
                    );

                    const content = section.content || "";
                    const paragraphs = content.split('\n').filter(p => p.trim());
                    paragraphs.forEach((para) => {
                        children.push(
                            new Paragraph({
                                children: [new TextRun({ text: para, size: 24 })],
                                spacing: { after: 160 },
                            })
                        );
                    });
                });
            }

            // Footer
            children.push(
                new Paragraph({
                    children: [
                        new TextRun({ text: 'Generated by PageCrafter AI — Doc Maker', size: 16, color: 'AAAAAA', italics: true }),
                    ],
                    spacing: { before: 800 },
                })
            );

            const docx = new Document({
                sections: [{ properties: {}, children }],
            });

            const blob = await Packer.toBlob(docx);
            const fileSaverLib = await import('file-saver');
            const saveAs = fileSaverLib.saveAs || (fileSaverLib as any).default;

            const cleanTitle = (doc.title || 'document').replace(/[/\\?%*:|"<>]/g, '-').trim();
            saveAs(new Blob([blob]), `${cleanTitle}.docx`);
            setIsShareMenuOpen(false);
        } catch (error) {
            console.error('Error exporting DOCX:', error);
            alert(`Failed to export document: ${error instanceof Error ? error.message : 'Unknown error'}`);
        }
    };

    if (isLoading && !doc) {
        return (
            <div className="flex-1 flex flex-col items-center justify-center bg-white gap-8">
                <HexagonalLoader size={120} color="#10b981" />
                <div className="flex flex-col items-center gap-2">
                    <span className="text-2xl font-black text-gray-900 tracking-tight">Writing Document</span>
                    <span className="text-emerald-500 font-bold animate-pulse text-sm uppercase tracking-widest">AI is composing your content...</span>
                </div>
            </div>
        );
    }

    if (!doc) {
        return (
            <div className="flex-1 flex flex-col items-center justify-center text-center p-12 bg-white">
                <div className="w-32 h-32 rounded-[3rem] bg-emerald-50 flex items-center justify-center text-emerald-500 mb-8 border border-emerald-100 shadow-xl">
                    <FileText className="w-16 h-16" />
                </div>
                <h2 className="text-3xl font-black text-gray-900 mb-4">Your Document Awaits</h2>
                <p className="text-gray-500 max-w-sm font-medium">Describe your requirements in the chat to generate a professional Word document. You can then edit and download it as .docx.</p>

                {history.length > 0 && (
                    <div className="mt-10 w-full max-w-md">
                        <h3 className="text-xs font-black text-gray-400 uppercase tracking-widest mb-4">Recent Documents</h3>
                        <div className="space-y-2">
                            {history.slice(0, 5).map((item) => (
                                <button
                                    key={item.id}
                                    onClick={() => loadFromHistory(item)}
                                    className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium text-gray-700 hover:bg-emerald-50 hover:text-emerald-700 transition-colors text-left border border-gray-100 group"
                                >
                                    <div className="w-8 h-8 rounded-lg bg-emerald-50 flex items-center justify-center text-emerald-500 group-hover:scale-110 transition-transform shrink-0">
                                        <FileText size={16} />
                                    </div>
                                    <div className="flex flex-col min-w-0 flex-1">
                                        <span className="truncate font-bold">{item.title}</span>
                                        <span className="text-[10px] text-gray-400">{new Date(item.createdAt).toLocaleDateString()}</span>
                                    </div>
                                </button>
                            ))}
                        </div>
                    </div>
                )}
            </div>
        );
    }

    return (
        <div className="flex-1 flex flex-col h-full bg-white overflow-hidden relative">
            {/* Header */}
            <div className="flex items-center justify-between px-8 py-4 bg-white border-b border-gray-200 z-10">
                <div className="flex items-center gap-4">
                    <span className="text-xs font-black text-gray-400 uppercase tracking-[0.2em]">Doc Maker</span>
                    <div className="h-4 w-px bg-gray-200" />
                    <h3 className="text-sm font-bold text-gray-800 truncate max-w-[200px]">{renderContent(doc.title)}</h3>
                </div>
                <div className="flex items-center gap-2">
                    {/* GrapesJS Toggle */}
                    <button
                        onClick={handleOpenEditor}
                        className="flex items-center gap-2 px-3 py-2 bg-emerald-50 text-emerald-700 hover:bg-emerald-100 rounded-xl text-xs font-bold transition-all border border-emerald-100"
                    >
                        <Edit3 size={14} />
                        <span>Edit with Editor</span>
                    </button>

                    <div className="w-px h-6 bg-gray-100 mx-2" />

                    {/* History Button */}
                    <div className="relative" ref={historyMenuRef}>
                        <button
                            onClick={() => setIsHistoryOpen(!isHistoryOpen)}
                            className="flex items-center gap-2 px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-xl text-xs font-bold transition-all"
                        >
                            <Clock size={14} />
                            <span className="hidden sm:inline">History</span>
                        </button>

                        {isHistoryOpen && (
                            <div className="absolute right-0 mt-2 w-72 bg-white border border-gray-200 rounded-2xl shadow-xl overflow-hidden z-[110] animate-fade-in">
                                <div className="p-3 border-b border-gray-100">
                                    <span className="text-xs font-black text-gray-400 uppercase tracking-widest">Document History</span>
                                </div>
                                <div className="max-h-64 overflow-y-auto p-2 space-y-1">
                                    {history.length === 0 ? (
                                        <p className="text-xs text-gray-400 p-3 text-center">No documents yet</p>
                                    ) : (
                                        history.map((item) => (
                                            <button
                                                key={item.id}
                                                onClick={() => loadFromHistory(item)}
                                                className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium text-gray-700 hover:bg-emerald-50 hover:text-emerald-700 transition-colors text-left group"
                                            >
                                                <div className="w-7 h-7 rounded-lg bg-emerald-50 flex items-center justify-center text-emerald-500 group-hover:scale-110 transition-transform shrink-0">
                                                    <FileText size={14} />
                                                </div>
                                                <div className="flex flex-col min-w-0 flex-1">
                                                    <span className="truncate font-bold text-xs">{item.title}</span>
                                                    <span className="text-[10px] text-gray-400">{new Date(item.createdAt).toLocaleDateString()}</span>
                                                </div>
                                            </button>
                                        ))
                                    )}
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Actions Button */}
                    <div className="relative" ref={shareMenuRef}>
                        <button
                            onClick={() => setIsShareMenuOpen(!isShareMenuOpen)}
                            className="flex items-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-black uppercase tracking-widest transition-all shadow-lg shadow-emerald-600/20 active:scale-95"
                        >
                            <Share2 size={14} />
                            Actions
                            <ChevronDown size={14} className={`transition-transform duration-200 ${isShareMenuOpen ? 'rotate-180' : ''}`} />
                        </button>

                        {isShareMenuOpen && (
                            <div className="absolute right-0 mt-2 w-56 bg-white border border-gray-200 rounded-2xl shadow-xl overflow-hidden z-[110] animate-fade-in">
                                <div className="p-2 space-y-1">
                                    <button
                                        onClick={handleExportDOCX}
                                        className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-bold text-gray-700 hover:text-gray-900 hover:bg-gray-50 transition-colors group text-left"
                                    >
                                        <div className="w-8 h-8 rounded-lg bg-emerald-50 flex items-center justify-center text-emerald-500 group-hover:scale-110 transition-transform">
                                            <Download size={16} />
                                        </div>
                                        <div className="flex flex-col">
                                            <span>Download .docx</span>
                                            <span className="text-[10px] text-gray-500 font-medium">Word document format</span>
                                        </div>
                                    </button>

                                    <button
                                        onClick={() => {
                                            if (doc) {
                                                saveToHistory(doc);
                                                setHistory(getHistory());
                                                alert('✅ Document saved to history!');
                                                setIsShareMenuOpen(false);
                                            }
                                        }}
                                        className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-bold text-gray-700 hover:text-gray-900 hover:bg-gray-50 transition-colors group text-left"
                                    >
                                        <div className="w-8 h-8 rounded-lg bg-indigo-50 flex items-center justify-center text-indigo-500 group-hover:scale-110 transition-transform">
                                            <Clock size={16} />
                                        </div>
                                        <div className="flex flex-col">
                                            <span>Save to History</span>
                                            <span className="text-[10px] text-gray-500 font-medium">Access anytime later</span>
                                        </div>
                                    </button>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* Preview Area */}
            <div className="flex-1 p-8 overflow-y-auto custom-scrollbar flex justify-center bg-gray-50">
                {doc.grapesHtml ? (
                    <div 
                        className="w-full max-w-[800px] bg-white text-gray-900 shadow-xl min-h-[1056px] relative overflow-hidden ring-1 ring-gray-200"
                        style={{ fontFamily: "'Inter', sans-serif", color: '#111827' }}
                    >
                        <style dangerouslySetInnerHTML={{ __html: `
                            #wrapper { padding: 48px; box-sizing: border-box; }
                            .emerald-title-block { border-bottom: 4px solid #059669; padding-bottom: 24px; margin-bottom: 32px; }
                            .emerald-title { font-size: 2.25rem; font-weight: 900; color: #111827 !important; margin: 0 0 8px 0 !important; text-transform: uppercase !important; letter-spacing: -0.05em !important; line-height: 1 !important; }
                            .emerald-meta { display: flex; justify-content: space-between; align-items: center; font-size: 0.875rem; font-weight: 700; color: #6b7280; text-transform: uppercase; letter-spacing: 0.1em; }
                            .emerald-heading-block { border-left: 4px solid #059669; padding: 4px 0 4px 16px; margin-bottom: 16px; }
                            .emerald-heading { font-size: 1.25rem; font-weight: 900; color: #059669 !important; text-transform: uppercase !important; letter-spacing: -0.025em !important; line-height: 1.2 !important; margin: 0 !important; }
                            p { line-height: 1.625; margin: 0; color: #374151; font-weight: 500; font-size: 1.125rem; }
                            ${doc.grapesCss || ''}
                        ` }} />
                        <div dangerouslySetInnerHTML={{ __html: doc.grapesHtml }} />
                    </div>
                ) : (
                    <div className="w-full max-w-[800px] h-max bg-white text-gray-900 p-12 shadow-sm min-h-[1056px] flex flex-col gap-8 rounded-sm ring-1 ring-gray-100">
                        {/* Legacy Preview */}
                        <div className="border-b-4 border-emerald-600 pb-6">
                            <h1 className="text-4xl font-black uppercase tracking-tighter text-gray-900 mb-2">
                                {renderContent(doc.title)}
                            </h1>
                            <div className="flex justify-between items-center text-sm font-bold text-gray-500 uppercase tracking-widest">
                                <span>By {doc.author || 'PageCrafter AI'}</span>
                                <span>{new Date().toLocaleDateString()}</span>
                            </div>
                        </div>

                        {doc.sections.map((section, idx) => (
                            <div key={idx} className="flex flex-col gap-4">
                                <div className="text-xl font-black uppercase tracking-tight text-emerald-600 border-l-4 border-emerald-600 pl-4 py-1">
                                    {renderContent(section.heading)}
                                </div>
                                <div className="text-lg leading-relaxed text-gray-700 font-medium whitespace-pre-wrap">
                                    {renderContent(section.content)}
                                </div>
                            </div>
                        ))}

                        <div className="mt-auto pt-10 border-t border-gray-100 flex justify-between items-center text-[10px] font-black uppercase tracking-[0.3em] text-gray-300">
                            <span>Generated by PageCrafter AI — Doc Maker</span>
                            <span>Page 1 of 1</span>
                        </div>
                    </div>
                )}
            </div>

            {/* GrapesJS Editor Portal */}
            {isEditorOpen && doc && (
                <WordDocEditor
                    html={doc.grapesHtml || convertToInitialHtml(doc)}
                    templateHtml={convertToInitialHtml(doc)}
                    onClose={() => setIsEditorOpen(false)}
                    onSave={handleSaveFromEditor}
                />
            )}

            <style jsx>{`
                .custom-scrollbar::-webkit-scrollbar { width: 4px; }
                .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
                .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(0,0,0,0.05); border-radius: 10px; }
            `}</style>
        </div>
    );
}
